spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
      format_sql: ${HIBERNATE_FORMAT_SQL}
      highlight_sql: ${HIBERNATE.HIGHLIGHT_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    show-sql: ${HIBERNATE_SHOW-SQL}
    open-in-view: ${JPA_OSIV}

springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}
    disable-swagger-default-url: ${SWAGGER_DISABLE_DEFAULT_URL}
    tags-sorter: ${SWAGGER_TAGS_SORTER}

auth:
  secret-key: ${SECRET_KEY}